# Running ONE command back in the interactive user's non-elevated context.
# Covered by: tests/Deelevate.Tests.ps1

function Get-WtInteractiveUserName {
    <#
    .SYNOPSIS
        The owner of the console session as DOMAIN\User, or '' when it
        cannot be read. Win32_ComputerSystem.UserName reports who is
        sitting at the machine regardless of what identity this process
        runs as, unlike $env:USERNAME under Start-Process -Verb RunAs.
        Never throws.
    #>
    param(
        [scriptblock]$GetConsoleUser = {
            (Get-CimInstance -ClassName Win32_ComputerSystem -ErrorAction Stop).UserName
        }
    )
    $owner = $null
    try { $owner = & $GetConsoleUser }
    catch { return '' }
    if ([string]::IsNullOrWhiteSpace([string]$owner)) { return '' }
    return ([string]$owner).Trim()
}

function ConvertTo-WtPsSingleQuoted {
    <#
    .SYNOPSIS
        One value as a PowerShell single-quoted literal, with every
        embedded quote doubled - the only escape a single-quoted string
        needs, keeping a package id from closing its own literal and
        continuing as script in the generated shim.
    #>
    param([Parameter(Mandatory)][AllowEmptyString()][string]$Value)
    return "'" + ([string]$Value).Replace("'", "''") + "'"
}

function New-WtInteractiveUserShim {
    <#
    .SYNOPSIS
        The little PowerShell script the scheduled task runs: it invokes
        one executable with one argument array, captures both streams to
        a file, and exits on the child's exit code. A shim file rather
        than a command line keeps the package id off a cmd.exe command
        line, where &, |, ^ and % would be live.
    #>
    param(
        [Parameter(Mandatory)][string]$FilePath,
        [Parameter(Mandatory)][AllowEmptyCollection()][AllowEmptyString()][string[]]$Arguments,
        [Parameter(Mandatory)][string]$OutputPath
    )
    $literals = @(foreach ($a in $Arguments) { ConvertTo-WtPsSingleQuoted -Value ([string]$a) })
    $argLine = if ($literals.Count -eq 0) { '@()' } else { '@(' + ($literals -join ', ') + ')' }
    $lines = @(
        '# Generated by WinToolify. Runs one command as the signed-in user; deleted afterwards.'
        '$ErrorActionPreference = ''Continue'''
        '$wtArgv = ' + $argLine
        '$wtExe = ' + (ConvertTo-WtPsSingleQuoted -Value $FilePath)
        '$wtOut = ' + (ConvertTo-WtPsSingleQuoted -Value $OutputPath)
        '& $wtExe @wtArgv 2>&1 | Out-File -LiteralPath $wtOut -Encoding utf8'
        '$wtCode = $LASTEXITCODE'
        'if ($null -eq $wtCode) { $wtCode = 1 }'
        'exit $wtCode'
    )
    return ($lines -join "`r`n")
}

function ConvertTo-WtTaskExitCode {
    <#
    .SYNOPSIS
        A scheduled task's LastTaskResult as a real exit code, or $null
        while the task has not produced one yet. LastTaskResult doubles as
        a status field before the action finishes (SCHED_S_TASK_RUNNING /
        HAS_NOT_RUN / QUEUED = 267009 / 267011 / 267045), so those three
        values are treated as "still working" rather than as exit codes;
        winget's own codes never collide with them.
    #>
    param([AllowNull()][object]$LastTaskResult)
    if ($null -eq $LastTaskResult) { return $null }
    $value = [int]$LastTaskResult
    if ($value -eq 267009 -or $value -eq 267011 -or $value -eq 267045) { return $null }
    return $value
}

function Get-WtSharedTextLines {
    <#
    .SYNOPSIS
        A text file's lines, read while something else still has it open
        for writing. Opens with FileShare::ReadWrite so a partial read is
        the worst case, never an exception - a plain Get-Content's share
        mode can lose that race. A file that is not there yet is zero
        lines.
    #>
    param([Parameter(Mandatory)][string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) { return , [string[]]@() }
    $stream = $null
    $reader = $null
    $text = ''
    try {
        $stream = New-Object System.IO.FileStream(
            $Path, [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read, [System.IO.FileShare]::ReadWrite)
        $reader = New-Object System.IO.StreamReader($stream, [System.Text.Encoding]::UTF8, $true)
        $text = $reader.ReadToEnd()
    }
    catch { return , [string[]]@() }
    finally {
        if ($null -ne $reader) { $reader.Dispose() }
        elseif ($null -ne $stream) { $stream.Dispose() }
    }
    if ($text -eq '') { return , [string[]]@() }
    return , [string[]]@($text -split "`r?`n")
}

function Get-WtInteractiveUserTaskApi {
    <#
    .SYNOPSIS
        The five Task Scheduler calls the runner needs, in one place, so
        every test can replace them together. Register-ScheduledTask with
        -LogonType Interactive and -RunLevel Limited builds the token from
        the principal rather than from whoever registered the task, so a
        task registered by an elevated process still runs at medium
        integrity in the user's own session, without needing a password.
    #>
    return @{
        Register = {
            param($Context)
            $action = New-ScheduledTaskAction -Execute 'powershell.exe' `
                -Argument ('-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "' + $Context.ShimPath + '"')
            $principal = New-ScheduledTaskPrincipal -UserId $Context.UserName `
                -LogonType Interactive -RunLevel Limited
            $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
                -ExecutionTimeLimit ([TimeSpan]::FromSeconds([Math]::Max(60, $Context.TimeoutSeconds)))
            $null = Register-ScheduledTask -TaskName $Context.TaskName -Action $action `
                -Principal $principal -Settings $settings -Force
        }
        Start    = { param($Context) Start-ScheduledTask -TaskName $Context.TaskName }
        State    = {
            param($Context)
            $task = Get-ScheduledTask -TaskName $Context.TaskName -ErrorAction SilentlyContinue
            if ($null -eq $task) { return '' }
            return [string]$task.State
        }
        Result   = {
            param($Context)
            $info = Get-ScheduledTaskInfo -TaskName $Context.TaskName -ErrorAction SilentlyContinue
            if ($null -eq $info) { return $null }
            return $info.LastTaskResult
        }
        Remove   = {
            param($Context)
            Unregister-ScheduledTask -TaskName $Context.TaskName -Confirm:$false -ErrorAction SilentlyContinue
        }
    }
}

function Invoke-WtProcessAsInteractiveUser {
    <#
    .SYNOPSIS
        Runs one executable in the signed-in user's non-elevated session
        and waits for it, returning its exit code and everything it
        printed. Needed because winget refuses to install, upgrade or
        uninstall a user-scoped package while running elevated
        (0x8A15007D); a scheduled task is the only mechanism that gives a
        medium-integrity token, the child's exit code, and its output
        without a P/Invoke into CreateProcessWithTokenW. Never throws -
        every failure mode comes back as Ran = $false with a Reason.
    #>
    param(
        [Parameter(Mandatory)][string]$FilePath,
        [Parameter(Mandatory)][AllowEmptyCollection()][AllowEmptyString()][string[]]$Arguments,
        [int]$TimeoutSeconds = 1800,
        [int]$PollMs = 400,
        [scriptblock]$OnOutput,
        [scriptblock]$GetUserName = { Get-WtInteractiveUserName },
        [string]$WorkRoot,
        [hashtable]$TaskApi,
        [switch]$KeepWorkFiles
    )
    $userName = [string](& $GetUserName)
    if ([string]::IsNullOrWhiteSpace($userName)) {
        return @{ Ran = $false; ExitCode = $null; Lines = [string[]]@(); Reason = 'NoInteractiveUser' }
    }

    $root = if ($WorkRoot) { [string]$WorkRoot } else { Join-Path ([System.IO.Path]::GetTempPath()) 'WinToolify' }
    if (-not (Test-Path -LiteralPath $root)) { $null = New-Item -ItemType Directory -Path $root -Force }
    $stamp = [Guid]::NewGuid().ToString('N').Substring(0, 12)
    $context = @{
        TaskName       = 'WinToolify-RunAsUser'
        UserName       = $userName
        ShimPath       = Join-Path $root ("runas-$stamp.ps1")
        LogPath        = Join-Path $root ("runas-$stamp.log")
        TimeoutSeconds = $TimeoutSeconds
    }
    $api = if ($TaskApi) { $TaskApi } else { Get-WtInteractiveUserTaskApi }

    $exitCode = $null
    $reason = ''
    try {
        Set-Content -LiteralPath $context.ShimPath -Encoding UTF8 -Value (
            New-WtInteractiveUserShim -FilePath $FilePath -Arguments $Arguments -OutputPath $context.LogPath)

        try {
            & $api.Register $context
            & $api.Start $context
        }
        catch { $reason = 'ScheduleFailed' }

        if ($reason -eq '') {
            $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
            while ($true) {
                Start-Sleep -Milliseconds ([Math]::Max(1, $PollMs))
                $state = [string](& $api.State $context)
                $raw = & $api.Result $context
                if ($OnOutput) { & $OnOutput (Get-WtSharedTextLines -Path $context.LogPath) }
                if ($state -ne 'Running') {
                    $exitCode = ConvertTo-WtTaskExitCode -LastTaskResult $raw
                    if ($null -ne $exitCode) { break }
                }
                if ((Get-Date) -ge $deadline) { $reason = 'Timeout'; break }
            }
        }
    }
    catch { $reason = 'ScheduleFailed' }
    finally {
        try { & $api.Remove $context } catch { }
    }

    $lines = Get-WtSharedTextLines -Path $context.LogPath
    if (-not $KeepWorkFiles) {
        foreach ($path in @($context.ShimPath, $context.LogPath)) {
            try { if (Test-Path -LiteralPath $path) { Remove-Item -LiteralPath $path -Force -ErrorAction SilentlyContinue } }
            catch { }
        }
    }

    if ($reason -ne '') { return @{ Ran = $false; ExitCode = $null; Lines = $lines; Reason = $reason } }
    return @{ Ran = $true; ExitCode = $exitCode; Lines = $lines; Reason = '' }
}

function Get-WtRetryReasonKey {
    <#
    .SYNOPSIS
        The translation key that explains why a de-elevated retry never
        ran. An unknown reason falls back to the general failure line
        rather than to a blank.
    #>
    param([Parameter(Mandatory)][AllowEmptyString()][string]$Reason)
    switch ($Reason) {
        'NoInteractiveUser' { return 'WsRetryNoUser' }
        'Timeout'           { return 'WsRetryTimeout' }
    }
    return 'WsRetryFailed'
}
